enum actionTypes {
    LOGIN = 'AUTH_LOGIN',
    LOGOUT = 'AUTH_LOGOUT',
    SET_CURRENT_SUDOKU = 'SET_CURRENT_SUDOKU',
    ADD_TO_SOLVED = 'ADD_SUDOKU_TO_SOLVED',
    SET_DIGIT = 'SET_DIGIT',
    SET_BOX = 'SET_BOX',
    DELETE_BOX = 'DELETE_BOX',
    DELETE_CURRENT_SUDOKU = 'DELETE_CURRENT_SUDOKU',
    ADD_TO_HISTORY = 'ADD_TO_HISTORY',
    RETURN_HISTORY = 'RETURN_HISTORY'
};

export default actionTypes;